# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  statuses:  # id of input
    description: 'A comma separated list of statuses to wait for'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.statuses }}
